### PR TITLE
Allow PHP 8, move tests to GitHub Actions

### PR DESCRIPTION
**Pull request by aleksblendwerk**
Short summary:

- Allows installation on PHP 8
- Moves CI to GitHub Actions, runs tests for PHP 7.3, 7.4 and 8.0
- Sets the PHPUnit version installed by `simple-phpunit` to 9.4 in `phpunit.xml.dist`
- The actual bundle or test code hasn't been touched at all

The badge in `README.md` should display right when this is merged - but from what I can see it will always display the status for the `master` branch - not sure if this was any different using Travis CI. There is a way to manually change the branch the badge refers to for long-running branches though.

I have also made a quick test using this version within `pingcrm-symfony` on PHP 8.0 and all seems fine.

### CODE REVIEW

**Comment by aleksblendwerk** [comment]
Hmm. I am not sure if the proposed GitHub Actions workflow was suppoosed to show up here as a check already. Might only be activated after you agreed on merging the PR. It is set to run on every push and PR.

**Comment by hvermeire** [comment]
Looks good, like always. Thanks @aleksblendwerk 😊

**Comment by rompetomp** [comment]
Thanks Aleks, looking good, like always!
I'll merge the PR, and we'll see if it will run the Github action :D

**Comment by aleksblendwerk** [comment]
Looking good, nice! 😇

**Pull request merged**
